# Generated by Django 4.2.1 on 2023-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('servings', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('ingredients', models.JSONField()),
                ('total_calories', models.FloatField()),
                ('total_protein', models.FloatField()),
                ('total_carbohydrates', models.FloatField()),
                ('calories_per_serving', models.FloatField()),
                ('is_public', models.BooleanField()),
            ],
        ),
    ]
